# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 06:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=11, unique=True)),
                ('otp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'REGISTERED'), (4, 'DEACTIVATED'), (5, 'WAITING_FOR_APPROVAL')], default=1)),
                ('role', models.IntegerField(choices=[(1, 'SELLER'), (2, 'ACCOUNT'), (3, 'ADMIN')], default=2)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('mobile', models.CharField(max_length=255)),
                ('imageUrl', models.CharField(max_length=255)),
                ('oneLiner', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.BigIntegerField()),
                ('uniqueId', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[(1, 'FACEBOOK'), (2, 'GOOGLE'), (3, 'MANUAL')], default=3)),
            ],
        ),
    ]
