# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(1, 'ACTIVE'), (2, 'INACTIVE'), (3, 'REGISTERED'), (4, 'DEACTIVATED'), (5, 'WAITING_FOR_APPROVAL')], default=1)),
                ('role', models.IntegerField(choices=[(1, 'SELLER'), (2, 'ACCOUNT'), (3, 'ADMIN')], default=2)),
            ],
        ),
    ]
