# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportId', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('date', models.DateTimeField()),
                ('startTime', models.BigIntegerField(blank=True)),
                ('endTime', models.BigIntegerField(blank=True)),
                ('deleted', models.BooleanField()),
                ('instructions', models.TextField()),
                ('sponser', models.IntegerField()),
                ('acceptor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acceptor', to='sports.User')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='sports.User')),
                ('requstors', models.ManyToManyField(related_name='requestors', to='sports.User')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=255)),
                ('lat', models.DecimalField(decimal_places=10, max_digits=20)),
                ('lng', models.DecimalField(decimal_places=10, max_digits=20)),
                ('deleted', models.BooleanField()),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.User')),
            ],
        ),
        migrations.AddField(
            model_name='opportunity',
            name='venueId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sports.Venue'),
        ),
    ]
