# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 11:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0002_auto_20171205_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opportunity',
            old_name='venueId',
            new_name='venue',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venue',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
