# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0005_auto_20171205_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='sponser',
        ),
        migrations.AddField(
            model_name='opportunity',
            name='sponsor',
            field=models.IntegerField(null=True),
        ),
    ]
