# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0007_user_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follower',
        ),
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='_user_follows_+', to='sports.User'),
        ),
    ]
