# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sports', '0008_auto_20171205_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to='sports.User'),
        ),
    ]
